### ISSUE TITLE
Verify release signatures

### ISSUE THREAD

**Issue by leoschwarz** [jat001/aur-firefox-developer#1]
Hi

Thanks for commenting on my AUR package firefox-developer-de, I always thought that it's rather silly having the many different language versions each be independently maintained with their own variations in the PKGBUILD.

The one thing I am missing from your PKGBUILD to feel comfortable handing over mine now is the lack of PGP signature checking when somebody builds the package. The way I did it is slightly hacky but it works and fails on a wrong signature https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firefox-developer-de#n39 , are you planning on including something like that in your PKGBUILDs too?

**Comment by jat001** [comment]
Thanks. I added [GPG verification](https://github.com/jat001/aur-firefox-developer/blob/master/common.sh#L39) to the script. I think it is not necessary to add it to PKGBUILD again.
